#!/usr/bin/env python3
# Convert extracted C4 icon PNGs (white/gray alpha masks on transparent) into a
# single LVGL C file of A8 (alpha-only) lv_image_dsc_t's. A8 icons are tinted at
# render time by the widget's image_recolor, so one asset serves every color
# (white on art, accent when active, etc.) -- same flexibility as a glyph font.
# Usage: png2lvgl.py <out.c> <name=png> [<name=png> ...]
#    or: png2lvgl.py <out.c> <manifest>   (a .manifest file: "id  relpath"
#        lines, paths relative to the manifest dir; '#' comments; blank lines ok)
# The generated header comment defaults to the C4-attribution text (matching the
# original icon set); set PNG2LVGL_HEADER to override it for a differently-
# licensed icon set (e.g. gen-ha-icons.sh's Material Design Icons attribution).
import os
import sys
from PIL import Image

def emit(name, path):
    im = Image.open(path).convert("RGBA")
    w, h = im.size
    a = im.split()[3]  # alpha channel = the mask
    data = a.tobytes()
    body = ",".join(str(b) for b in data)
    return w, h, data, f"static const uint8_t {name}_map[] = {{{body}}};\n"

out = sys.argv[1]
if len(sys.argv) == 3 and sys.argv[2].endswith(".manifest"):
    mdir = os.path.dirname(os.path.abspath(sys.argv[2]))
    items = []
    for line in open(sys.argv[2]):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        name, rel = line.split(None, 1)
        items.append([name, os.path.join(mdir, rel.strip())])
else:
    items = [arg.split("=", 1) for arg in sys.argv[2:]]
header = os.environ.get("PNG2LVGL_HEADER") or (
    "/* Generated by tools/icons/png2lvgl.py -- real Control4 X4 icons\n"
    " * (licensed via the partner agreement), A8 alpha masks tinted at\n"
    " * render time. Do not edit by hand. */\n"
)
with open(out, "w") as f:
    f.write(header)
    f.write('#include "lvgl.h"\n\n')
    for name, path in items:
        w, h, data, blob = emit(name, path)
        f.write(blob)
        f.write(f"const lv_image_dsc_t icon_{name} = {{\n")
        f.write("  .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8,\n")
        f.write(f"             .w = {w}, .h = {h}, .stride = {w}, .flags = 0 }},\n")
        f.write(f"  .data_size = sizeof({name}_map),\n  .data = {name}_map,\n}};\n\n")
print(f"wrote {out} with {len(items)} icons")
