/* Embedded Roboto TTF bytes (Apache-2.0), for lv_tiny_ttf runtime font
 * scaling. See mmk_roboto.c (generated by tools/fonts/embed-roboto.sh). */
#pragma once
#include <stdint.h>

extern const uint8_t mmk_roboto_regular[];
extern const unsigned int mmk_roboto_regular_len;
extern const uint8_t mmk_roboto_medium[];
extern const unsigned int mmk_roboto_medium_len;
