/* Embedded Lucide icon-subset TTF (MIT), for lv_tiny_ttf icon scaling. See
 * mmk_lucide.c (generated by tools/fonts/embed-lucide.sh). */
#pragma once
#include <stdint.h>

extern const uint8_t mmk_lucide[];
extern const unsigned int mmk_lucide_len;
